version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "stickers_db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: 123
    ports:
      - 5444:5432
    volumes:
      - ./docker-data/data:/var/lib/postgresql/data

  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8088:8080